name: Create a release pull-request via release-please-cli
on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version'
        required: false
      last_tag_sha:
        description: 'Last release SHA'
        required: false

jobs:
  release_via_release_please_cli:
    runs-on: ubuntu-latest
    name: release_via_release_please_cli
    env:
      GITHUB_TOKEN:  ${{ secrets.GITHUB_TOKEN }}
      OWNER: ${{ github.repository_owner }}
        # REPO: ${{ github.event.repository.name }}
        # github.event.repository.name is null in act. See: https://github.com/actions/runner/issues/2473
        # This bug will be fixed in https://github.com/nektos/act/issues/2019
      REPO: github-release-example
    steps:
      - name: Check out Repository
        id: check_out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node JS
        id: setup_node_js
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: "npm"
      - name: Install JS dependencies
        run: |
          npm install release-please -g
      - name: Create/Update release PRs
        if: github.event_name == 'workflow_dispatch'
        run: |
          release-please release-pr ${{ github.event.inputs.release_version && format('--release-as={0}', github.event.inputs.release_version)  || '' }} ${{ github.event.inputs.last_tag_sha && format('--latest-tag-sha={0}', github.event.inputs.last_tag_sha) || '' }} --token=$GITHUB_TOKEN --repo-url=$OWNER/$REPO

