name: Create a release pull-request
on:
  workflow_dispatch:
jobs:
  release_pr:
    runs-on: ubuntu-latest
    name: release_pull_request
    steps:
      - name: Check out Repository
        id: check_out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node JS
        id: setup_node_js
        uses: actions/setup-node@v3
        with:
          # node-version: latest
          node-version: 16.x
          cache: "npm"
      - name: Install JS dependencies
        run: |
          npm install @actions/core @actions/github mustache
      - name: "Create Pull Request"
        run: |
          node .github/src/create_release_pr.js
        env:
          GITHUB_TOKEN:  ${{ secrets.GITHUB_TOKEN }}
          BASE_BRANCH: release
          HEAD_BRANCH: main
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
          LABELS: "release"
          TEMPLATE: ".github/git-pr-release.template"
