on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: update-release-pr

jobs:
  update-release-pr:
    runs-on: ubuntu-latest
    steps:
      - run: echo "test"
        if: github.event.action === 'synchronize'
      # - uses: google-github-actions/release-please-action@v3
      #   with:
      #     command: release-pr
      #     release-type: node
      #     package-name: github-release-example

