on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: update-release-pr

jobs:
  update-release-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        if: github.event.action == 'synchronize' && github.event.label.name == 'autorelease: pending'
        with:
          command: release-pr
          release-type: node
          package-name: github-release-example

